allowBuilds:
  '@prisma/client': set this to true or false
  '@prisma/engines': set this to true or false
  '@swc/core': true
  contentlayer2: true
  esbuild: true
  prisma: set this to true or false
  protobufjs: true
  sharp: true
