// Single entry point for every table, consumed by the Drizzle client and drizzle-kit.
//
// - auth.ts    → generated by `pnpm auth:generate` (core + admin + organization/teams + stripe).
//                Never edit by hand: change lib/auth/server.ts, then regenerate.
// - other files → app tables. Every business table carries a non-null `organizationId`.

export * from "./auth"
